/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/lib')['Button']
    ACheckbox: typeof import('ant-design-vue/lib')['Checkbox']
    App: typeof import('./src/App.vue')['default']
    ASpace: typeof import('ant-design-vue/lib')['Space']
    Dashboard: typeof import('./src/views/Dashboard/index.vue')['default']
    Greet: typeof import('./src/components/Greet.vue')['default']
    Home: typeof import('./src/views/Home/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Leftbar: typeof import('./src/components/Layout/leftbar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NMenu: typeof import('naive-ui')['NMenu']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
